"""
Initial dataset cleaning for boolean-flag labels: dedupe, drop noise, enforce
quality gates, and emit a small statistics report (JSON).

Expects:
- Label JSONL from `boolean_flag_roles.py extract` with optional `source_row`
  (1-based input line index, recommended so duplicate repo/path rows resolve to the
  correct snippet). Without `source_row`, the cleaner joins on `(repo, path)` using
  the first occurrence in the canonical file only.
- The same canonical JSONL (in the same line order) used when labels were produced.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sqlite3
import tempfile
from collections import Counter
from pathlib import Path
from typing import Any

from tqdm import tqdm

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CLEAN = PROJECT_ROOT / "outputs" / "labeled" / "boolean_flags_clean.jsonl"
DEFAULT_STATS = PROJECT_ROOT / "outputs" / "labeled" / "boolean_flags_clean.stats.json"

_AUTOGEN_RES = [
    re.compile(r"auto[-_\s]?generated", re.I),
    re.compile(r"do\s+not\s+(edit|modify)", re.I),
    re.compile(r"this\s+file\s+was\s+generated", re.I),
    re.compile(r"@generated\b", re.I),
    re.compile(r"\bgenerated\s+by\b", re.I),
]


def _is_autogenerated(code: str) -> bool:
    head = code[:8000]
    if any(r.search(head) for r in _AUTOGEN_RES):
        return True
    return False


def _is_notebook_artifact(path: str, code: str) -> bool:
    pl = path.lower()
    if "ipynb" in pl or ".ipynb_checkpoints" in pl:
        return True
    if "get_ipython(" in code or "IPython." in code:
        return True
    return False


def _non_empty_line_count(s: str) -> int:
    return sum(1 for ln in s.splitlines() if ln.strip())


def _find_top_level_function(
    tree: ast.Module, name: str
) -> ast.FunctionDef | ast.AsyncFunctionDef | None:
    for stmt in tree.body:
        if isinstance(stmt, (ast.FunctionDef, ast.AsyncFunctionDef)) and stmt.name == name:
            return stmt
    return None


def _count_name_occurrences(fn: ast.FunctionDef | ast.AsyncFunctionDef, var: str) -> int:
    n = 0
    for node in ast.walk(fn):
        if isinstance(node, ast.Name) and node.id == var:
            n += 1
        elif isinstance(node, ast.arg) and node.arg == var:
            n += 1
    return n


def _build_canonical_db(
    conn: sqlite3.Connection,
    canonical_path: Path,
    max_rows: int | None,
) -> int:
    conn.execute("DROP TABLE IF EXISTS canon")
    conn.execute("DROP TABLE IF EXISTS canon_rp")
    conn.execute(
        "CREATE TABLE canon (idx INTEGER NOT NULL PRIMARY KEY, "
        "repo TEXT NOT NULL, path TEXT NOT NULL, code TEXT NOT NULL)"
    )
    conn.execute(
        "CREATE TABLE canon_rp (repo TEXT NOT NULL, path TEXT NOT NULL, code TEXT NOT NULL, "
        "PRIMARY KEY (repo, path))"
    )
    n = 0
    batch: list[tuple[int, str, str, str]] = []
    with canonical_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            row = json.loads(line)
            repo = row.get("repo") or ""
            path = row.get("path") or ""
            code = row.get("code") or ""
            n += 1
            batch.append((n, repo, path, code))
            if len(batch) >= 4096:
                conn.executemany(
                    "INSERT INTO canon (idx, repo, path, code) VALUES (?,?,?,?)",
                    batch,
                )
                conn.executemany(
                    "INSERT OR IGNORE INTO canon_rp (repo, path, code) VALUES (?,?,?)",
                    [(a[1], a[2], a[3]) for a in batch],
                )
                batch.clear()
            if max_rows is not None and n >= max_rows:
                break
    if batch:
        conn.executemany(
            "INSERT INTO canon (idx, repo, path, code) VALUES (?,?,?,?)",
            batch,
        )
        conn.executemany(
            "INSERT OR IGNORE INTO canon_rp (repo, path, code) VALUES (?,?,?)",
            [(a[1], a[2], a[3]) for a in batch],
        )
    conn.commit()
    return n


def _lookup_code_by_idx(conn: sqlite3.Connection, idx: int) -> str | None:
    cur = conn.execute("SELECT code FROM canon WHERE idx = ? LIMIT 1", (idx,))
    row = cur.fetchone()
    return row[0] if row else None


def _lookup_code_by_repo_path(conn: sqlite3.Connection, repo: str, path: str) -> str | None:
    cur = conn.execute(
        "SELECT code FROM canon_rp WHERE repo = ? AND path = ? LIMIT 1", (repo, path)
    )
    row = cur.fetchone()
    return row[0] if row else None


def clean_boolean_labels(
    *,
    labels_path: Path,
    canonical_path: Path,
    out_labels_path: Path,
    out_stats_path: Path,
    max_label_rows: int | None = None,
    max_canonical_rows: int | None = None,
    top_k: int = 40,
) -> dict[str, Any]:
    dropped: Counter[str] = Counter()
    seen: set[tuple[str, str, str, str]] = set()

    parse_cache: dict[tuple[Any, ...], ast.Module | None] = {}
    parse_err_cache: set[tuple[Any, ...]] = set()

    role_counts: Counter[str] = Counter()
    var_freq: Counter[str] = Counter()
    repo_freq: Counter[str] = Counter()

    n_in = 0
    n_out = 0

    with tempfile.NamedTemporaryFile(suffix=".sqlite", delete=False) as tmp:
        db_path = tmp.name
    try:
        conn = sqlite3.connect(db_path)
        canon_n = _build_canonical_db(conn, canonical_path, max_canonical_rows)

        out_labels_path.parent.mkdir(parents=True, exist_ok=True)

        with labels_path.open(encoding="utf-8") as fin, out_labels_path.open(
            "w", encoding="utf-8"
        ) as fout:
            pbar = tqdm(desc="clean labels", unit="line")
            for line in fin:
                line = line.strip()
                if not line:
                    continue
                n_in += 1
                pbar.update(1)
                rec = json.loads(line)
                if rec.get("parse_error"):
                    dropped["parse_error_row"] += 1
                    continue
                role = rec.get("role")
                if role != "boolean_flag":
                    dropped["non_boolean_role"] += 1
                    continue
                repo = rec.get("repo")
                path = rec.get("path")
                fn_name = rec.get("function")
                var = rec.get("variable")
                if not repo or not path or not fn_name or not var:
                    dropped["missing_fields"] += 1
                    continue

                sr = rec.get("source_row")
                if sr is not None:
                    try:
                        idx = int(sr)
                    except (TypeError, ValueError):
                        dropped["bad_source_row"] += 1
                        continue
                    dedupe_key = (idx, fn_name, var)
                    code = _lookup_code_by_idx(conn, idx)
                    cache_key: tuple[Any, ...] = ("idx", idx)
                else:
                    dedupe_key = (repo, path, fn_name, var)
                    code = _lookup_code_by_repo_path(conn, repo, path)
                    cache_key = ("rp", repo, path)

                if dedupe_key in seen:
                    dropped["duplicate"] += 1
                    continue

                if code is None:
                    dropped["missing_canonical"] += 1
                    continue

                if _is_notebook_artifact(path, code):
                    dropped["notebook_artifact"] += 1
                    continue
                if _is_autogenerated(code):
                    dropped["autogenerated"] += 1
                    continue

                if cache_key in parse_err_cache:
                    dropped["malformed_canonical"] += 1
                    continue

                tree = parse_cache.get(cache_key)
                if tree is None:
                    try:
                        tree = ast.parse(code, mode="exec")
                    except SyntaxError:
                        parse_err_cache.add(cache_key)
                        dropped["malformed_canonical"] += 1
                        continue
                    parse_cache[cache_key] = tree

                fn = _find_top_level_function(tree, fn_name)
                if fn is None:
                    dropped["no_matching_function"] += 1
                    continue

                if _non_empty_line_count(code) < 5:
                    dropped["short_function"] += 1
                    continue

                if _count_name_occurrences(fn, var) < 2:
                    dropped["variable_few_occurrences"] += 1
                    continue

                seen.add(dedupe_key)
                fout.write(json.dumps(rec, ensure_ascii=False) + "\n")
                n_out += 1
                role_counts[role] += 1
                var_freq[var] += 1
                repo_freq[repo] += 1

                if max_label_rows is not None and n_in >= max_label_rows:
                    break
            pbar.close()

        stats: dict[str, Any] = {
            "canonical_rows_indexed": canon_n,
            "input_label_lines_read": n_in,
            "output_label_lines": n_out,
            "dropped": dict(dropped),
            "role_counts": dict(role_counts),
            "top_variables": var_freq.most_common(top_k),
            "top_repositories": repo_freq.most_common(top_k),
        }
        out_stats_path.parent.mkdir(parents=True, exist_ok=True)
        out_stats_path.write_text(json.dumps(stats, indent=2), encoding="utf-8")
    finally:
        conn.close()
        Path(db_path).unlink(missing_ok=True)

    return stats


def _cmd(args: argparse.Namespace) -> int:
    stats = clean_boolean_labels(
        labels_path=Path(args.labels),
        canonical_path=Path(args.canonical),
        out_labels_path=Path(args.output),
        out_stats_path=Path(args.stats_output),
        max_label_rows=args.max_label_rows,
        max_canonical_rows=args.max_canonical_rows,
        top_k=args.top_k,
    )
    print(json.dumps({k: stats[k] for k in ("input_label_lines_read", "output_label_lines", "dropped")}, indent=2))
    print(f"stats -> {args.stats_output}")
    print(f"labels -> {args.output}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(description="Clean boolean-flag label JSONL using canonical source.")
    p.add_argument("--labels", type=str, required=True, help="boolean_flags.jsonl from boolean_flag_roles.py")
    p.add_argument("--canonical", type=str, required=True, help="Matching canonical CodeSearchNet JSONL")
    p.add_argument("--output", type=str, default=str(DEFAULT_CLEAN))
    p.add_argument("--stats-output", type=str, default=str(DEFAULT_STATS))
    p.add_argument("--max-label-rows", type=int, default=None)
    p.add_argument("--max-canonical-rows", type=int, default=None, help="Dev only: index first N canonical rows.")
    p.add_argument("--top-k", type=int, default=40, help="Top K entries in variable/repo frequency tables.")
    args = p.parse_args()
    return _cmd(args)


if __name__ == "__main__":
    raise SystemExit(main())
